spring.application.name=java_agent
server.port = 8080
openai.api-key=${OPENAI_API_KEY:ollama}
openai.base-url=${OPENAI_BASE_URL:http://localhost:11434/v1}
openai.model=${OPENAI_MODEL:qwen2.5:7b}

server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-binding-errors=always
